name: Docker Image CI API

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Oracle OCIR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.OCI_REGISTRY }}
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.OCI_REGISTRY }}/${{ secrets.OCI_NAMESPACE }}/priceapp
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            latest
            
      - name: Replace secrets in appsettings files
        run: |
          sed -i \
            -e "s/DB_HOST/${{ secrets.DB_HOST }}/g" \
            -e "s/DB_USERNAME/${{ secrets.DB_USERNAME }}/g" \
            -e "s/DB_PASSWORD/${{ secrets.DB_PASSWORD }}/g" \
            -e "s/JWT_SECRET_KEY/${{ secrets.JWT_SECRET_KEY }}/g" \
            -e "s/EMAIL_LOGIN_EMAIL/${{ secrets.EMAIL_LOGIN_EMAIL }}/g" \
            -e "s/EMAIL_PASS/${{ secrets.EMAIL_PASS }}/g" \
            -e "s/EMAIL_SMTP_SERVER/${{ secrets.EMAIL_SMTP_SERVER }}/g" \
            ./priceapp.API/appsettings.json

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./priceapp.API/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
